# Generated by Django 4.0.3 on 2022-03-19 01:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RekodHarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_name_buy', models.CharField(max_length=500)),
                ('item_type', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('unit_of_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.unitofmeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='RekodBlokchain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('prev_hash', models.CharField(max_length=300)),
                ('data_hash', models.CharField(max_length=300)),
                ('data_signature', models.CharField(max_length=300)),
                ('public_key', models.CharField(max_length=300)),
                ('nonce', models.IntegerField()),
                ('hash_id', models.CharField(max_length=300)),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.rekodharga')),
            ],
        ),
    ]
