# Generated by Django 4.0.3 on 2022-03-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekodblokchain',
            name='transaction_id',
        ),
    ]
