# Generated by Django 4.0.3 on 2022-04-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rekodblokchain',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='rekodharga',
            options={'ordering': ('timestamp',)},
        ),
    ]
