# Generated by Django 4.0.3 on 2022-04-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_rekodblokchain_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekodblokchain',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
