# Generated by Django 4.0.3 on 2022-04-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_rekodblokchain_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekodblokchain',
            name='data_signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
