# Generated by Django 4.0.3 on 2022-03-19 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_rekodharga_timestamp_rekodblokchain_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekodharga',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
