# Generated by Django 4.0.3 on 2022-04-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rekodblokchain_flag_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekodblokchain',
            name='public_key',
            field=models.CharField(max_length=420),
        ),
    ]
