# Generated by Django 4.0.3 on 2022-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_private_key_alter_profile_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
